name: sample_pj
description: "donuts sample_pj."
version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  donuts_annotation: ^0.0.3
  flutter_riverpod: ^2.4.10
  uuid: ^4.3.3
  http: ^1.2.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
dev_dependencies:
  donuts:
    path: ../donuts

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  analyzer: ^6.2.0
  build_runner: ^2.4.8

flutter:
