targets:
  $default:
    builders:
      # ------------------------------------------------------------
      # factory
      # ------------------------------------------------------------
      donuts|abstractInterfaceFactoryBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|factoryImplBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|factoryProviderBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      # ------------------------------------------------------------
      # repository
      # ------------------------------------------------------------
      donuts|abstractInterfaceRepositoryBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|repositoryImplBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|inMemoryRepositoryImplBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|repositoryProviderBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      # ------------------------------------------------------------
      # application service
      # ------------------------------------------------------------
      donuts|abstractInterfaceApplicationServiceBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|applicationServiceImplBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|applicationServiceProviderBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      # ------------------------------------------------------------
      # state
      # ------------------------------------------------------------
      donuts|listStateBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|singleStateBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      # ------------------------------------------------------------
      # view
      # ------------------------------------------------------------
      donuts|listViewBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|detailViewBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"
      donuts|createModalBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/domain/*"
            - "lib/domain/**/*"

builders:
  # ------------------------------------------------------------
  # factory
  # ------------------------------------------------------------
  donuts|abstractInterfaceFactoryBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/factory/{{file}}.abstract_interface_factory.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceFactoryBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|factoryImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/factory/{{file}}.factory_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["factoryImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|factoryProviderBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/factory/{{file}}.factory_provider.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["factoryProviderBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # repository
  # ------------------------------------------------------------
  donuts|abstractInterfaceRepositoryBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.abstract_interface_repository.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceRepositoryBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|repositoryImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.repository_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["repositoryImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|inMemoryRepositoryImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.in_memory_repository_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["inMemoryRepositoryImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|repositoryProviderBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.repository_provider.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["repositoryProviderBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # application service
  # ------------------------------------------------------------
  donuts|abstractInterfaceApplicationServiceBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/application_service/{{file}}.abstract_interface_application_service.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceApplicationServiceBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|applicationServiceImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/application_service/{{file}}.application_service_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["applicationServiceImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|applicationServiceProviderBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/application_service/{{file}}.application_service_provider.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["applicationServiceProviderBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # state
  # ------------------------------------------------------------
  donuts|listStateBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/state/{{file}}.list_state_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["listStateBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|singleStateBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/state/{{file}}.single_state_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["singleStateBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # view
  # ------------------------------------------------------------
  donuts|listViewBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/view/{{file}}.list_view.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["listViewBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|detailViewBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/view/{{file}}.detail_view.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["detailViewBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|createModalBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/view/{{file}}.create_modal.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["createModalBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
