targets:
  $default:
    builders:
      # ------------------------------------------------------------
      # factory
      # ------------------------------------------------------------
      donuts|abstractInterfaceFactoryBuilder:
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|factoryImplBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/factory/src/test_data/{{file}}.factory_impl.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|factoryProviderBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/factory/src/test_data/{{file}}.factory_provider.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      # ------------------------------------------------------------
      # repository
      # ------------------------------------------------------------
      donuts|abstractInterfaceRepositoryBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/repository/src/test_data/{{file}}.abstract_interface_repository.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|repositoryImplBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/repository/src/test_data/{{file}}.repository_impl.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|inMemoryRepositoryImplBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/repository/src/test_data/{{file}}.in_memory_repository_impl.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|repositoryProviderBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/repository/src/test_data/{{file}}.repository_provider.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|abstractInterfaceApiBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/repository/api/src/test_data/{{file}}.abstract_interface_api.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|apiImplBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/repository/api/src/test_data/{{file}}.api_impl.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"

      # ------------------------------------------------------------
      # application service
      # ------------------------------------------------------------
      donuts|abstractInterfaceApplicationServiceBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/application_service/src/test_data/{{file}}.abstract_interface_application_service.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|applicationServiceImplBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/application_service/src/test_data/{{file}}.application_service_impl.dart"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      donuts|applicationServiceProviderBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/application_service/src/test_data/{{file}}.application_service_provider.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
        enabled: true
        generate_for:
          include:
            - "lib/src/test_data/*"
            - "lib/src/test_data/**/*"
      # ------------------------------------------------------------
      # state
      # ------------------------------------------------------------
      donuts|listStateBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/state/src/test_data/{{file}}.list_state_impl.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
      donuts|singleStateBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/state/src/test_data/{{file}}.single_state_impl.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
      # ------------------------------------------------------------
      # view
      # ------------------------------------------------------------
      donuts|listViewBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/view/src/test_data/{{file}}.list_view.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
      donuts|detailViewBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/view/src/test_data/{{file}}.detail_view.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"
      donuts|createModalBuilder:
        options:
          build_extensions:
            "^lib/src/test_data/{{file}}.dart": "lib/donuts/view/src/test_data/{{file}}.create_modal.dart"
          api_domain: "https://xxx.example.com"
          api_version: "v99"

builders:
  # ------------------------------------------------------------
  # factory
  # ------------------------------------------------------------
  donuts|abstractInterfaceFactoryBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/factory/{{file}}.abstract_interface_factory.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceFactoryBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|factoryImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/factory/{{file}}.factory_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["factoryImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|factoryProviderBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/factory/{{file}}.factory_provider.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["factoryProviderBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # repository
  # ------------------------------------------------------------
  donuts|abstractInterfaceRepositoryBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.abstract_interface_repository.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceRepositoryBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|repositoryImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.repository_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["repositoryImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|inMemoryRepositoryImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.in_memory_repository_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["inMemoryRepositoryImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|repositoryProviderBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/{{file}}.repository_provider.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["repositoryProviderBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|abstractInterfaceApiBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/api/{{file}}.abstract_interface_api.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceApiBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["method_to_swagger_yaml|swaggerYamlBuilder"]
  donuts|apiImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/repository/api/{{file}}.api_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["apiImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["method_to_swagger_yaml|swaggerYamlBuilder"]

  # ------------------------------------------------------------
  # application service
  # ------------------------------------------------------------
  donuts|abstractInterfaceApplicationServiceBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/application_service/{{file}}.abstract_interface_application_service.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["abstractInterfaceApplicationServiceBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|applicationServiceImplBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/application_service/{{file}}.application_service_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["applicationServiceImplBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|applicationServiceProviderBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/application_service/{{file}}.application_service_provider.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["applicationServiceProviderBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # state
  # ------------------------------------------------------------
  donuts|listStateBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/state/{{file}}.list_state_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["listStateBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|singleStateBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/state/{{file}}.single_state_impl.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["singleStateBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # ------------------------------------------------------------
  # view
  # ------------------------------------------------------------
  donuts|listViewBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/view/{{file}}.list_view.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["listViewBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|detailViewBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/view/{{file}}.detail_view.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["detailViewBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  donuts|createModalBuilder:
    defaults:
      options:
        build_extensions:
          "^lib/{{file}}.dart": "lib/donuts/view/{{file}}.create_modal.dart"
    import: "package:donuts/donuts.dart"
    builder_factories: ["createModalBuilder"]
    build_extensions: {}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
