builders:
  donuts|swaggerYamlBuilder:
    import: "package:donuts/builder.dart"
    builder_factories: ["abstractInterfaceFactoryBuilder"]
    build_extensions: { ".dart": [".abstract_interface_factory.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
