name: donuts
description: "donuts.focus ui. focus domain modeling."
version: 0.0.4
repository: https://github.com/powerboo/donuts.git

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  analyzer: ">=5.13.0 <7.0.0"
  build: ^2.4.1
  built_collection: ^5.1.1
  build_config: ^1.1.1
  dart_style: ^2.3.2
  donuts_annotation: ^0.0.3
  code_builder: ^4.10.0
  freezed_annotation: ^2.4.1
  path: ^1.9.0
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.2.2
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  source_gen_test: ^1.0.6
  test: ^1.21.0
