name: donuts
description: "donuts.focus ui. focus domain modeling."
version: 0.2.5
repository: https://github.com/powerboo/donuts.git

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <7.0.0"
  annotation_indexer_annotation: ^0.0.1 # un used. only use declared import path
  build: ^2.4.1
  built_collection: ^5.1.1
  build_config: ^1.1.1
  dart_style: ^2.3.2
  donuts_annotation: ^0.2.0
  code_builder: ^4.10.0
  freezed_annotation: ">=2.0.0 <3.0.0"
  path: ">=1.8.1 <2.0.0"
  source_gen: ^1.2.7
  method_to_swagger_yaml_annotation: ^0.0.1
dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.2.2
  source_gen_test: ^1.0.6
  test: ^1.21.0

  uuid: ^4.3.3
  freezed: ^2.4.7
  riverpod: ^2.5.0
  hooks_riverpod: ^2.4.10
  http: ^1.2.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  method_to_swagger_yaml: ^0.0.5
  # expect_error: ^1.0.4
